spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener?TimeZone=UTC
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  # 🆕 changed
    consumer:
      group-id: click-analytics-group                                                # 🆕 changed
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer  # 🆕 changed
      properties:
        spring:
          json:
            trusted:
              packages: "com.url_shortner.url_shortner.kafka"                        # 🆕 added

app:
  base-url: http://localhost:8080
  short-code-length: 7
  cache-ttl-seconds: 3600
  rate-limit:
    max-requests: 10
    window-seconds: 60

kafka:
  topic:
    click-events: click-events                                                       # 🆕 added

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics